module main

// Generated by Haxe

struct ArrayTest {
}

fn main() {
	{
		mut numbers_0 := 1
		mut numbers_1 := 2
		mut numbers_2 := 3
		mut numbers_3 := 4
		mut numbers_4 := 5
		mut first := numbers_0
		println('First number: ' + first.str())
	}
}
