module main

// Generated by Haxe

struct ArrayTest {
}

fn main() {
	{
		numbers_0 := 1
		numbers_1 := 2
		numbers_2 := 3
		numbers_3 := 4
		numbers_4 := 5
		first := numbers_0
		println('First number: ' + first.str())
	}
}
