module main

// Generated by Haxe

struct ArrayLiteralTest {
}

fn main() {
	{
		mut numbers_0 := 1
		mut numbers_1 := 2
		mut numbers_2 := 3
		mut numbers_3 := 4
		mut numbers_4 := 5
		println('First number: ' + numbers_0.str())
		println('Last number: ' + numbers_4.str())
		mut fruits_0 := "apple"
		mut fruits_1 := "banana"
		mut fruits_2 := "orange"
		println('First fruit: ' + fruits_0.str())
		println('Second fruit: ' + fruits_1.str())
		mut mixed_0 := 10
		mut mixed_1 := 20
		mut mixed_2 := 30
		mut sum := mixed_0 + mixed_1 + mixed_2
		println('Sum: ' + sum.str())
	}
}
