module main

// Generated by Haxe

struct ComparisonTest {
}

fn main() {
	{
		mut a := 10
		mut b := 20
		if (a < b) {
			println('a is less than b')
}
		if (a == 10) {
			println('a equals 10')
}
		if (b != a) {
			println('b is not equal to a')
}
	}
}
