module main

// Generated by Haxe

struct ConditionalTest {
}

struct Std {
}

fn main() {
	{
		x := 10
		if (x > 5) {
			println('x is greater than 5')
} else {
			println('x is less than or equal to 5')
}
	}
}
