module main

// Generated by Haxe

enum Color {
	blue
	green
	r_g_b { r int; g int; b int }
	red
}

enum Direction {
	east
	north
	south
	west
}

struct EnumTest {
}

fn get_color_name(color Color) string {
	// TODO: Switch (Switch statement not implemented)
}

fn move_point(x int, y int, dir Direction) string {
	// TODO: Switch (Switch statement not implemented)
}

fn main() {
	{
		mut simple_color := // TODO: type expression.red
		println('Simple color: ' + (get_color_name(simple_color)).str())
		mut complex_color := // TODO: type expression.r_g_b(255, 128, 64)
		println('Complex color: ' + (get_color_name(complex_color)).str())
		mut direction := // TODO: type expression.north
		println(move_point(5, 5, direction))
		println(move_point(10, 10, // TODO: type expression.east))
	}
}
