module main

// Generated by Haxe

struct ForInTest {
}

fn main() {
	{
		mut numbers := [1, 2, 3, 4, 5]
		println('Numbers:')
		{
			mut _g := 0
			for (_g < numbers.length) {
				mut num := numbers[_g]
				_g++
				println('Number: ' + num.str())
			}
		}
		mut fruits := ["apple", "banana", "orange"]
		println('Fruits:')
		{
			mut _g := 0
			for (_g < fruits.length) {
				mut fruit := fruits[_g]
				_g++
				println('Fruit: ' + fruit.str())
			}
		}
		println('Range 0-4:')
		{
			println('Index: ' + '0')
			println('Index: ' + '1')
			println('Index: ' + '2')
			println('Index: ' + '3')
			println('Index: ' + '4')
		}
	}
}
