module main

// Generated by Haxe

struct FunctionTest {
}

fn greet(name string) string {
	return "Hello " + name
}

fn main() {
	{
		result := // type expression for class FunctionTest.greet("V World")
		println(result)
	}
}
