module main

// Generated by Haxe

struct MathTest {
}

fn add(a int, b int) int {
	return a + b
}

fn multiply(x f64, y f64) f64 {
	return x * y
}

fn factorial(n int) int {
	if n <= 1 {
		return 1
}
	return n * factorial(n - 1)
}

fn main() {
	{
		println('Addition: ' + (add(5, 3)).str())
		println('Multiplication: ' + (multiply(2.5, 4.0)).str())
		println('Factorial of 5: ' + (factorial(5)).str())
		mut result := add(10, 20)
		println('Stored result: ' + result.str())
	}
}
