module main

// Generated by Haxe

struct Point {
	x int
	y int
}

fn (self &Point) get_distance() f64 {
	return sqrt(self.x * self.x + self.y * self.y)
}

fn (self &Point) to_string() string {
	return "Point(" + self.x + ", " + self.y + ")"
}

struct ObjectTest {
}

fn main() {
	{
		mut p1 := Point { x: 3, y: 4 }
		println('Point 1: ' + (p1.to_string()).str())
		mut p2 := Point { x: 0, y: 0 }
		println('Point 2: ' + (p2.to_string()).str())
		mut origin := Point { x: 5, y: 12 }
		println('Distance from origin: ' + (origin.get_distance()).str())
	}
}
