module main

// Generated by Haxe

struct RecursionTest {
}

fn fibonacci(n int) int {
	if n <= 1 {
		return n
}
	return fibonacci(n - 1) + fibonacci(n - 2)
}

fn power(base int, exp int) int {
	if exp == 0 {
		return 1
}
	return base * power(base, exp - 1)
}

fn main() {
	{
		println('Fibonacci 10: ' + (fibonacci(10)).str())
		println('2^5 = ' + (power(2, 5)).str())
		println('3^4 = ' + (power(3, 4)).str())
	}
}
