module main

// Generated by Haxe

struct SimpleTypeTest {
}

fn main() {
	{
		mut int_val := 42
		println('Integer: ' + int_val.str())
		mut float_val := 3.14
		println('Float: ' + float_val.str())
		mut bool_val := true
		if bool_val {
			println('Boolean is true')
} else {
			println('Boolean is false')
}
		mut str_val := "Haxe to V"
		println('String: ' + str_val.str())
		mut sum := int_val + 10
		println('Sum: ' + sum.str())
		mut product := float_val * 2.0
		println('Product: ' + product.str())
	}
}
