module main

// Generated by Haxe

struct Person {
	name string
	age int
}

fn (self &Person) greet() string {
	return "Hello, I am " + self.name + " and I am " + (self.age).str() + " years old"
}

struct SimpleObjectTest {
}

fn main() {
	{
		mut person := Person { name: "Alice", age: 25 }
		mut greeting := person.greet()
		println(greeting)
	}
}
