module main

// Generated by Haxe

struct TypeTest {
}

fn main() {
	{
		mut int_val := 42
		println('Integer: ' + int_val.str())
		mut float_val := 3.14
		println('Float: ' + float_val.str())
		mut bool_val := true
		println('Boolean: ' + (string(bool_val)).str())
		mut str_val := "Haxe to V"
		println('String: ' + str_val.str())
		mut int_to_float := int_val
		println('Int to Float: ' + int_to_float.str())
		mut nullable_str := unsafe { nil }
		if (nullable_str == unsafe { nil }) {
			println('String is null')
}
		nullable_str = "Not null anymore"
		if (nullable_str != unsafe { nil }) {
			println('String is not null: ' + nullable_str.str())
}
	}
}
